### ISSUE TITLE
No sound after resuming from sleep

### ISSUE THREAD

**Issue by that-itguy** [mrfixit2001/debian_desktop#10]
Noticed I no longer have sound after resuming from sleep. A reboot fixes the issue.

**Comment by that-itguy** [comment]
Tested just now using Chromium and navigating to Youtube. Sound was playing after reboot. Suspended by using Fn+ESC and choosing "suspend". Closed lid and came back opened lid and hit power button to wake. Youtube no longer had sound. Neither did twitter notifications that were open in another tab. 
Also tried to play a local file to rule out the browser. The local file also produced no sound.

**Comment by fretinator** [comment]
I can confirm this and it is easily reproducible. Opening PulseAudio after suspend, and then playing audio causes the meter in PulseAudio to move back and forth with the sound. To me, this means it is not a software issue, as PulseAudio is receiving appropriate levels from the app. It appears the sound hardware does not wake up. I did try disabling and re-enabling the mic with the Pine-F10 combination just to see if that might cause the sound hardware to wake up but it doesn't. As noted above, you must reboot for sound to resume working. [kern.log](https://github.com/mrfixit2001/debian_desktop/files/3693689/kern.log)

**Comment by fretinator** [comment]
I also tested using alsamixer. Before sleep, you can select the internal sound (es8316) or the HDMI sound to view controls for each device. After suspend and resume, you can still view the HDMI device, but if you select the internal sound card (ES8316), it crashes and says no device found.

**Comment by mrfixit2001** [comment]
Thank you for reporting, I have confirmed the bug and am working on the resolution. 
In the meantime, please confirm if you have encountered this issue on the pinebook or the rockpro release.

**Comment by fretinator** [comment]
Pinebook ProOn Oct 14, 2019 21:17, mrfixit2001 <notifications@github.com> wrote:Thank you for reporting, I have confirmed the bug and am working on the resolution.
In the meantime, please confirm if you have encountered this issue on the pinebook or the rockpro release.

**Comment by that-itguy** [comment]
This is on the recently released PineBook Pro

**Comment by mrfixit2001** [comment]
I have pushed an update to the repo to resolve this - please click the update icon (looks like a target) on the bottom right of your desktop and it will install a kernel update which resolves. It will also install a script on your desktop to update the widevine libraries any time that netflix and amazon prime require a newer version.

**Comment by fretinator** [comment]
Done, confirmed working.On Oct 15, 2019 13:34, mrfixit2001 <notifications@github.com> wrote:I have pushed an update to the repo to resolve this - please click the update icon (looks like a target) on the bottom right of your desktop and it will install a kernel update which resolves. It will also install a script on your desktop to update the widevine libraries any time that netflix and amazon prime require a newer version.

**Comment by mrfixit2001** [comment]
If you pulled that fix already then you'll want to do another quick update so your battery doesn't drain faster than it should due to the governor being set to performance. Thanks for confirming, everything is good to go now.

**Comment by fretinator** [comment]
Yeah, I noticed that and just set it back to on demand.On Oct 15, 2019 16:24, mrfixit2001 <notifications@github.com> wrote:If you pulled that fix already then you'll want to do another quick update so your battery doesn't drain faster than it should due to the governor being set to performance. Thanks for confirming, everything is good to go now.

**Comment by iav** [comment]
After sleep (by lid closing) chromium plays video as a slideshow — frame-by frame, 1-2 frame per second, and without a sound.
Close and run chromium again solves the problem.
Isit related, or should I open another bug?

**Comment by louisabraham** [comment]
Hi, I have the same bug on my ANSI pinebook pro: sound works when booting (in both VLC and Chromium). After sleep, it doesn't work anymore.
Additionally, PulseAudio never works to test the speakers.

**Comment by mrfixit2001** [comment]
This also should be addressed by the updates available when you run the updater.

**Comment by louisabraham** [comment]
Hi, I can confirm I ran the updater before reporting the bug. It currently says that no updates are available. The sound still doesn't work after sleep.
