### ISSUE TITLE
Enable KVM

### ISSUE THREAD

**Issue by colemancda** [mrfixit2001/debian_desktop#20]
I wanted to request enabling KVM in the kernel for future builds, to run other ARM64 OS like Android and Windows 10.

Where can I find the source and instructions for building the kernel you are shipping? I could try to modify the kernel configuration myself and update the kernel on my Pinebook Pro instead of flashing a new image.

**Comment by mrfixit2001** [comment]
I have updated the kernel and pushed an update. The new kernel has virtualization and kvm enabled, by request. :)

**Comment by mrfixit2001** [comment]
Kernel source is in my repo: 
https://github.com/mrfixit2001/rockchip-kernel

**Comment by colemancda** [comment]
Thank you so much!
