### ISSUE TITLE
is it possible to boot from nvme?

### ISSUE THREAD

**Issue by plumlis** [mrfixit2001/debian_desktop#21]
I has been trying to move the rootfs to the SSD(nvme) with my Pinebook Pro
after edit the bootfile (extlinux.conf) to point to the SSD instead to the emmc the PBP refuse to boot.

**Comment by mrfixit2001** [comment]
Rockchip's U-Boot does not yet provide drivers to support booting off of PCIe / NVME. We hope it is added in the future.
