### ISSUE TITLE
Is it Possible to boot from a NVME disk mounted on the RockPro64 adapter?

### ISSUE THREAD

**Issue by sbfreddie** [mrfixit2001/debian_desktop#23]
I have tried all the various methods described that I could find with a google search, but none of them work on the distro.

Help!

Thanks,
Freddie

**Comment by mrfixit2001** [comment]
It is now! I just pushed v1.9 which updates uboot to allow for NVME boot

**Comment by sbfreddie** [comment]
mrfixit:
How do I make this work on your current distro (191226) for the rockpro64?
How do I install these newer kernel's and u-boot?

Thanks,
Ed
