### ISSUE TITLE
Enable dm-crypt module

### ISSUE THREAD

**Issue by e-minguez** [mrfixit2001/debian_desktop#24]
The current kernel doesn't have the dm-crypt module compiled, do you mind to enable it?

Thanks.

**Comment by mrfixit2001** [comment]
All set in the latest kernel commits as well as in the latest v1.9 update
https://github.com/mrfixit2001/rockchip-kernel/commit/894797839eb10d326224a96e7d8bb1dd261aa32a#diff-24e009d21d0f79e30a7b16a3f2ffaba0
