### ISSUE TITLE
Emulation?

### ISSUE THREAD

**Issue by ghost** [mrfixit2001/debian_desktop#25]
Any way to emulate this fork, like a VM, for testing?

**Comment by mrfixit2001** [comment]
It's just like any other distro, so you could run it in a docker container for sure. Here's an example of where a user took my recalbox release for the rockpro and created a docker container for it to run. You'd need to do the same thing.

https://github.com/digitalsanity/recalbox-in-docker

**Comment by ghost** [comment]
I meant something like QEMU, since QEMU supports emulating ARM? And if so, how would I best set up QEMU for this? I've tried a couple ways that don't quite seem to work. Or is Docker the best bet here?
