### ISSUE TITLE
screen blank after changing resolution

### ISSUE THREAD

**Issue by dominictarr** [mrfixit2001/debian_desktop#26]
the screen resolution on the pinebook pro is much higher than I am used to, making all the text small and unpleasant to read. I tried changing it to something smaller, using the displays tool under preferences. but the screen went blank! and I couldn't see anything.

computer was now unusable. luckily the logon screen still appeared after a reset.

I managed to fix it by logging into a TTY with `ctrl-alt-F1` then creating a new user `sudo useradd test` then restarting and logging in as `test`. I tried using the "apply system wide" button on the displays tool to fix it but that didn't work. but logging in again via tty I managed to find the config file that set the resolution. I copied `sudo cat /home/test/.config/monitors.xml > /home/MYSELF/.config/monitors.xml`

really... there needs to be a timer and a button that confirms the resolution, and if you don't click it it resets. I don't know what resolutions don't work or not but 1024*768 definitely didn't.

**Comment by mrfixit2001** [comment]
The eDP screen on the pinebook pro only supports 1080p, so changing the resolution unfortunately cannot be done. You can, however, change the settings inside of Mate to make the font and icons larger.
