### ISSUE TITLE
PCIe Driver/Support - gasket-dkms (RockPro64)

### ISSUE THREAD

**Issue by mummpydo** [mrfixit2001/debian_desktop#29]
Attempting to utilize RockPro64 PCIe slot  

Unable to install package due to missing linux-headers. - lspci -t => [0000:00]

**Comment by digitalsanity** [comment]
You will need to work with the kernel repo here:
https://github.com/mrfixit2001/rockchip-kernel

The Kernel Customization section here is helpful - http://students.engr.scu.edu/~sschaeck/misc/pinebookpro.html

This will give you a deb with the latest kernel and a new package for corresponding headers that you can install.

Next, use the armhf instructions here to enable DKMS -- https://github.com/ayufan-rock64/linux-build/blob/master/recipes/dkms.md --

- Referencing this thread may help -- https://forum.pine64.org/showthread.php?tid=8225

**Comment by digitalsanity** [comment]
If you only need DKMS support, this might work (armhf instructions) - https://github.com/ayufan-rock64/linux-build/blob/master/recipes/dkms.md

**Comment by mrfixit2001** [comment]
This is how you add the kernel headers on the build:
git clone https://github.com/mrfixit2001/rockchip-kernel
cd rockchip-kernel
make -j5 INSTALL_HDR_PATH=/lib/modules/$(uname -r)/build headers_install
