### ISSUE TITLE
KDE Variant Sponsorship Offer

### ISSUE THREAD

**Issue by MarekPasnikowski** [mrfixit2001/debian_desktop#32]
I have saved up money with intention to sponsor some development.

I decided I would like to have the KDE variant of this distribution sponsored.

How much is such work worth? I don't know if I will be able to afford it, but I'd like to try.

Am not that good with words, so please don't mind my style much.

**Comment by MarekPasnikowski** [comment]
Due to no response at all and current global situation, I am considering to close this issue.

**Comment by mrfixit2001** [comment]
@Obikawa I have just emailed your GitHub email to discuss further.

**Comment by mrfixit2001** [comment]
The email bounced back. So I'll paste it here:
Thank you for reaching out to my GitHub repository about the potential to sponsor the development for a KDE variant of my debian desktop. I apologize for my late reply, as I did not see the issue opened until today. I have been concentrating my work on kernel development for the past couple months.

What are your goals of the KDE variant? What time frame would you be hoping for? What budget do you have to work with?
