### ISSUE TITLE
dmidecode fails with a segmentation fault

### ISSUE THREAD

**Issue by simonboydfoley** [mrfixit2001/debian_desktop#4]
Running on RockPro64 emmc 64bit
dmidecode fails 

Message from syslogd@rockpro64-0 at Jun 22 19:32:51 ...
 kernel:[26077.432637] Process dmidecode (pid: 2742, stack limit = 0xffffffc0d8784000)
Segmentation fault

**Comment by mrfixit2001** [comment]
Not sure how to reproduce this - please confirm if resolved on latest release and reopen with more detail if issue persist. Thank you!
