### ISSUE TITLE
Kernel Mainlining & LTS

### ISSUE THREAD

**Issue by Izaic** [mrfixit2001/debian_desktop#5]
What's the reason for the old 4.4 kernel? No mainline for the rockchip SOC used for the pinebook pro? Or is it the gpu? (or both)

This seems like it's going to be a big security and longevity problem to be using a old kernel.

I imagine the panfrost drivers are usable enough that they'd be okay for basic video and desktop?

**Comment by schaecsn** [comment]
The  4.4 kernel here is a  fork from Rockchip https://github.com/rockchip-linux/kernel. Perhaps ask the Rockchip community why they don't keep up with mainline.

Note, 4.4 is a longterm kernel so security is not a problem (yet).
