### ISSUE TITLE
[Security Issue] Image do ship `ssh_host_keys`

### ISSUE THREAD

**Issue by ayufan** [mrfixit2001/debian_desktop#6]
It seems that images do ship a number of data that should not be part of:
1. generated ssh host keys,
2. a number of `/var/log` files.

At least the 1. can be considered a security issue and bad practice: https://missingm.co/2013/07/identical-droplets-in-the-digitalocean-regenerate-your-ubuntu-ssh-host-keys-now/ and https://blog.digitalocean.com/avoid-duplicate-ssh-host-keys/.

I also wonder if images were trimmed.

**Comment by mrfixit2001** [comment]
ayufan: thank you for pointing these out! They are fixed in the next release, will leave open until I can get that pushed

**Comment by ayufan** [comment]
Yes, but how you ensure that there are fixed in any future release? :)

Do you have checklist of items to validate before pushing images?

**Comment by mrfixit2001** [comment]
Yes :) And I have added the ssh clear and regen into the boot script to run only on first boot.

**Comment by mrfixit2001** [comment]
Resolved in latest release
